config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView

# from django.views.generic import TemplateView
from django.views import defaults as default_views
from home.views import HomeView


urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path('', HomeView.as_view(), name="home"),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("initpy.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('i18n/', include('django.conf.urls.i18n')),
    path("robots.txt/", TemplateView.as_view(template_name="initpy/robots.txt")),
    path("sitemap.xml/", TemplateView.as_view(template_name="initpy/sitemap.xml")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

initpy/users/urls.py
from django.urls import path

from initpy.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

home/models.py
from django.db import models

# Create your models here.

initpy/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from sorl.thumbnail import ImageField


class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    photo = ImageField(upload_to="team", blank=True, verbose_name=_("Photo"))
    birth_day = models.DateField(null=True, blank=True, verbose_name=_("Birth day"))

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def __str__(self):
        return "{0} {1} ({2})".format(self.first_name, self.last_name, self.username)

team_app/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from sorl.thumbnail import ImageField

from django.conf import settings
# Create your models here.

User = settings.AUTH_USER_MODEL


class TeamModel(models.Model):
    user = models.ForeignKey(User, related_name="team", on_delete=models.CASCADE, verbose_name=_("User"))
    skills = RichTextField(verbose_name=_("skills"))
    position = models.CharField(max_length=200, blank=True, verbose_name=_("position"))

    def __str__(self):
        return self.user.__str__()

    class Meta:
        verbose_name = _("team member")
        verbose_name_plural = _("Team members")


class ContactModel(models.Model):
    phone = models.CharField(max_length=12, verbose_name=_("phone"))
    fax = models.CharField(max_length=12, blank=True, verbose_name=_("fax"))
    address = models.TextField(verbose_name=_("address"))
    email = models.EmailField(verbose_name=_("E-mail"))

    def __str__(self):
        return "{0} {1} {2}".format(self.phone, self.fax, self.email)

    class Meta:
        verbose_name = _("contact")
        verbose_name_plural = _("contacts")


class ServiceModel(models.Model):
    icon = models.CharField(max_length=50, verbose_name=_("icon style"))
    title = models.CharField(max_length=250, verbose_name=_("type of service"))
    desc = RichTextField(verbose_name=_("description"))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("service")
        verbose_name_plural = _("service list")


class AboutModel(models.Model):
    title = models.CharField(max_length=250, verbose_name=_("title"))
    body = RichTextField(verbose_name=_('body'))

    class Meta:
        verbose_name = _("about")
        verbose_name_plural = _("abouts")


class CertificatesModel(models.Model):
    user = models.ForeignKey(TeamModel, on_delete=models.CASCADE, related_name="cert", verbose_name=_("Team member"))
    image = ImageField(upload_to="team/certificates/", blank=True, verbose_name=_("Image"))

    def __str__(self):
        return self.user.__str__()

    class Meta:
        verbose_name = _("certificate")
        verbose_name_plural = _("certificate list")

initpy/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

team_app/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from team_app.models import TeamModel


class TeamForm(forms.ModelForm):
    skills = forms.CharField(widget=CKEditorWidget)

    class Meta:
        model = TeamModel
        fields = '__all__'

home/views.py
from django.views.generic import TemplateView
# Create your views here.


class HomeView(TemplateView):
    template_name = "pages/home.html"

initpy/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

team_app/views.py
from django.shortcuts import render

# Create your views here.

initpy/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

initpy/templates/lng_menu.html
{% load i18n %}

<form class="navbar-form navbar-right" action="{% url 'set_language' %}" method="post">{% csrf_token %}
  <div class="form-group">
    <input class="form-control" name="next" type="hidden" value="{{ redirect_to }}" />
  </div>
  
  <select name="language">
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    {% for language in languages %}
    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
      {{ language.name_local }} ({{ language.code }})
    </option>
    {% endfor %}
  </select>
 
  <input type="submit" class="btn btn-default navbar-btn" value="{% trans 'Change' %}" />
</form>

initpy/templates/pages/about.html
{% extends "base.html" %}

initpy/templates/pages/home.html
{% extends "base.html" %}
{% load static i18n thumbnail %}

{% block service %}
<div class="container">
  <div class="row">
    <h4>{% trans 'Services' %}</h4>
    <h2>{% trans 'List of services provided' %}</h2>
    <img class="img-responsive" src="{% static '/images/daag.png' %}" alt="">
    
    {% for item in services %}
    <div class="col-md-3 wow zoomIn animated">
      <i class="{{ item.icon }}"></i>
      <h3>{{ item.title }}</h3>
      {{ item.desc|safe }}
    </div>
    {% endfor %}
    
  </div>
</div>
{% endblock service%}


{% block team %}
<div class="container">  
  <div class="row">
    
    <div class="pricing-slide-heading text-center">
      <h4>{% trans 'Primary assets are people' %}</h4>
      <h2>{% trans 'Team members' %}</h2>
      <img class="img=responsive" src="{% static '/images/daag.png' %}" alt="">
    </div>
    
    <div class="the-pricing-slider">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
	  <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
	  <li data-target="#carousel-example-generic" data-slide-to="1"></li>
	  <li data-target="#carousel-example-generic" data-slide-to="2"></li>
	</ol>
	
	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
	  <div class="item active">
	    {% for item in team_members %}
	    <div class="col-md-6 col-xs-12 col-sm-12 wow zoomIn animated">
	      
	      <div class="person">
		{% thumbnail item.user.photo "100x100" crop="center" as im %}
		<img class="img-circle img-responsive" src="{{im.url}}" alt="">
		{% endthumbnail %}
		<h6>{{item.user.first_name}} {{item.user.last_name}}</h6>
		<h5>{{ item.position }}</h5>
		<p>{{ item.skills|safe }}</p>
	      </div>
	      
	    </div>
	    {% endfor %}
	  </div>
	</div>

      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block contact %}
<div class="container">
  <div class="row">
    <div class="contact-heading">
      <h4>{% trans 'stay in touch' %}</h4>
      <h2>{% trans 'Contacts' %}</h2>
      <img class="img-responsive" src="{% static '/images/daag.png' %}" alt="">
    </div>
    
    {% for item in contacts %}
    <div class="col-md-2 col-md-offset-1 col-xs-4 col-sm-4">
      <i class="fa fa-phone"></i>
      <p>Phone: {{item.phone}}</p>
      {% if item.fax %}}
      <p>Fax: {{item.fax}}</p>
      {% endif %}
    </div>
    <div class="col-md-4 col-md-offset-1 col-xs-4 col-sm-4">
      <i class="fa fa-map-marker"></i>
      <p>{{ item.address }}</p>
    </div>
    <div class="col-md-3 col-md-offset-1 col-xs-4 col-sm-4 clearfix">
      <i class="fa fa-envelope-o"></i>
      <p>{{ item.email}}</p>
    </div>
    {% endfor contacts %}
    
    <div class="col-md-8 col-md-offset-2 col-xs-12 col-sm-12">
      <article class="contact-form">
	<form action="contact">
	  <div class="col-md-5 col-md-offset-1 contact-form-left">
	    <input class="name" type="text" placeholder="NAME*">
	    <input class="email" type="email" placeholder="EMAIL*">
	    <input class="subject" type="text" placeholder="SUBJECT*">
	  </div>
	  <div class="col-md-5 contact-form-right text-right">
	    <textarea class="message" name="message" id="message" cols="30" rows="10" placeholder="MESSAGE"></textarea>
	    <input type="submit" class="submit-btn" value="send message">
	  </div>
	</form>
      </article>
    </div>
  </div>
</div>
{% endblock contact %}

{% block about %}
<div class="container">
  <div class="row">
    
    <div class="col-md-6 col-xs-12 col-sm-12 wow slideInUp animated">
      {% for item in abouts %}    
      <h4>dip into the details</h4>
      <h2>{{item.title}}</h2>
      <img class="img-responsive" src="{% static '/images/daag.png' %}" alt="">
      {{item.body|safe}}
      {% endfor %}      
    </div>
    
    <div class="col-md-6 col-xs-12 col-sm-12 wow slideInUp animated">
      
      {% for item in certs %}    
      <div class="col-md-6 col-xs-12 col-sm-12 wow slideInUp animated">
	{% thumbnail item.image "288x200" crop="center" as im %}
	<a href="#" data-toggle="modal" data-target=".cert-{{item.id}}">
	  <img class="img-responsive" src="{{im.url}}" alt="">
	</a>
	{% endthumbnail %}
      </div>
      {% endfor %}
      
    </div>

  </div>
</div>

{% for item in certs %}
<div class="modal fade cert-{{item.id}}" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h5 class="modal-title">{{item.user.position}}: {{item.user.user.first_name}} {{item.user.user.last_name}}</h5>
      </div>
      
      <div class="modal-body">
	{% thumbnail item.image "720" crop="center" as im %}
	<img class="img-responsive" src="{{im.url}}" alt="">
	{% endthumbnail %}
      </div>
      
    </div>
  </div>
</div>
{% endfor %}

{% endblock about %}

initpy/templates/top_menu.html
{% load static i18n thumbnail %}

<nav class="navbar navbar-default">
  <div class="container-fluid nav-bar">
    <div class="navbar-header">
      
      <a class="navbar-brand" href="#">
	<img class="logo img-responsive" src="{% static '/images/logo.png' %}" alt="Brand">
      </a>

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	<span class="sr-only">Toggle navigation</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
      <!-- <a href="/"><img src="{% static '/images/logo.png' %}" alt="" class="img-responsive logo"></a> -->
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
	<li><a href="#home">{% trans 'Main' %}</a></li>
	<li><a href="#service">{% trans 'Service' %}</a></li>
	<li><a href="#about">{% trans 'About as'%}</a></li>
	<li><a href="#team">{% trans 'Team members' %}</a></li>
	<!-- <li><a href="#pricing">{% trans 'Prices'%}</a></li> -->
	<li><a href="#contact">{% trans 'Contacts' %}</a></li>
      {% include 'lng_menu.html' %}
      </ul>
    </div>
  </div>
</nav>

initpy/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

initpy/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

initpy/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}